graph TD
    Important[Important?]
    Important -->|No| ImportantNo[Not important. Urgent?]
    Important -->|Yes| ImportantYes[Yes. Urgent?]
    ImportantNo -->|No| ImportantNoUrgentNo[Not important nor urgent. Trash it!]
    ImportantNo -->|Yes| ImportantNoUrgentYes[Important: no. Urgent? Yes. Delegate!]
    ImportantYes -->|No| ImportantYesUrgentNo[Not urgent. But important. Actionable?]

    ImportantYesUrgentNo -->|Yes| ImportantYesUrgentNoActionableYes[Yes. Add to backlog. Don't trash it but don't worry about the details - i.e. multi or single step task etc.]
    ImportantYesUrgentNo -->|No| ImportantYesUrgentNoActionableNo[No. Can you delegate this task and let someone else develop/incubate it?]
    ImportantYesUrgentNoActionableNo -->|No| ImportantYesUrgentNoActionableNoDelegateNo[No. Is this really worth cluttering your backlog? If it as incubating/etc in backlog. Don't worry about the details. Is it a docs task? Something to keep for reference? Then put it somewhere where whoever needs the information can access it and stop it from cluttering your backlog.]

    ImportantYes -->|Yes| ImportantYesUrgentYes[Yes, it's urgent. Actionable?]
    ImportantYesUrgentYes -->|Yes| ImportantYesUrgentYesActionableYes[Yes. Single step task?]
    ImportantYesUrgentYes -->|No| ImportantYesUrgentYesActionableNo[No. ]
    ImportantYesUrgentYesActionableYes -->ImportantYesUrgentYesActionableYesSingleStepTaskYes[Yes. Done in 2 min?]
    ImportantYesUrgentYesActionableYes -->ImportantYesUrgentYesActionableYesSingleStepTaskNo[No.]
    ImportantYesUrgentYesActionableYesSingleStepTaskYes -->ImportantYesUrgentYesActionableYesSingleStepTaskYesDoneIn2Mins[Yes. Do it now]
    ImportantYesUrgentYesActionableYesSingleStepTaskYes -->ImportantYesUrgentYesActionableYesSingleStepTaskYesNotDoneIn2Mins[No. Delegate to someone else?]
    ImportantYesUrgentYesActionableYesSingleStepTaskYesNotDoneIn2Mins -->ImportantYesUrgentYesActionableYesSingleStepTaskYesNotDoneIn2MinsDelegateNo[No. Do it yourself?]
    ImportantYesUrgentYesActionableYesSingleStepTaskYesNotDoneIn2MinsDelegateNo -->ImportantYesUrgentYesActionableYesSingleStepTaskYesNotDoneIn2MinsDelegateNoDoItYourselfNo[No. Put this away somewhere.]
    ImportantYesUrgentYesActionableYesSingleStepTaskYesNotDoneIn2MinsDelegateNo -->ImportantYesUrgentYesActionableYesSingleStepTaskYesNotDoneIn2MinsDelegateNoDoItYourselfYes[Yes. Do you have time for it now?]
    ImportantYesUrgentYesActionableYesSingleStepTaskYesNotDoneIn2MinsDelegateNoDoItYourselfYes -->ImportantYesUrgentYesActionableYesSingleStepTaskYesNotDoneIn2MinsDelegateNoDoItYourselfYesTimeForItNowYes[Yes. Do it now!]
    ImportantYesUrgentYesActionableYesSingleStepTaskYesNotDoneIn2MinsDelegateNoDoItYourselfYes -->ImportantYesUrgentYesActionableYesSingleStepTaskYesNotDoneIn2MinsDelegateNoDoItYourselfYesTimeForItNowNo[No. Add this to TODO ASAP _or_ schedule it]